run:
  dims: [10, 10]
  ranges: 
    - [0.0, 1.0]
    - [0.0, 1.0]
  sigma: 0.1
  sigma0: 0.1
  iterations: 300
  batch_size: 100
  num_emitters: 2
  bounds: [-2.0, 2.0]
  learning_rate: 0.01
tasks:
  C:
    task: CartPole-v1
    nodes: [4, 4, 2]
    threshold: 500
  M:
    task: MountainCar-v0
    nodes: [2, 8, 3]
    threshold: -110
  L:
    task: LunarLander-v3
    nodes: [8, 8, 4]
    threshold: 200